// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace br.com.foo.kafka.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Cliente : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Cliente\",\"namespace\":\"br.com.foo.kafka.avro\",\"fields\":[{" +
				"\"name\":\"clienteId\",\"doc\":\"id do cliente\",\"type\":\"string\"},{\"name\":\"name\",\"doc\":\"" +
				"nome do cliente\",\"type\":\"string\"}],\"version\":\"1\"}");
		/// <summary>
		/// id do cliente
		/// </summary>
		private string _clienteId;
		/// <summary>
		/// nome do cliente
		/// </summary>
		private string _name;
		public virtual Schema Schema
		{
			get
			{
				return Cliente._SCHEMA;
			}
		}
		/// <summary>
		/// id do cliente
		/// </summary>
		public string clienteId
		{
			get
			{
				return this._clienteId;
			}
			set
			{
				this._clienteId = value;
			}
		}
		/// <summary>
		/// nome do cliente
		/// </summary>
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.clienteId;
			case 1: return this.name;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.clienteId = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
